### ISSUE TITLE
meshctl install --dry-run fails 

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo-mesh#1140] opened 2020-12-12 17:46 UTC
**Describe the bug**
meshctl install --dry-run fails due to crds not being registered

**To Reproduce**
```bash
meshctl install --dry-run

DEBU[0001] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: installing gloo-mesh: installing helm chart: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Settings" in version "settings.mesh.gloo.solo.io/v1alpha2"
```

**Additional context**
- Gloo Mesh v0.10.8

**Comment by joekelley** [comment] 2020-12-13 19:21
duplicate of #1106

**Closed by joekelley** 2020-12-13 19:21 UTC
Labels: Type: Bug
