### ISSUE TITLE
Formatting of YAML examples on Gloo Mesh api reference documentation are on single lines

### ISSUE THREAD

**Issue by Freaky-namuH** [solo-io/gloo-mesh#1946] opened 2022-08-19 23:54 UTC
### Version

main

### Describe the requested changes

The YAML examples on the page https://docs.solo.io/gloo-mesh-enterprise/latest/reference/api/github.com.solo-io.gloo-mesh-enterprise.api.gloo.solo.io.admin.v2.workspace_settings/#admin.gloo.solo.io.WorkspaceSettingsSpec are all on a single line

### Link to any relevant existing docs

https://docs.solo.io/gloo-mesh-enterprise/latest/reference/api/github.com.solo-io.gloo-mesh-enterprise.api.gloo.solo.io.admin.v2.workspace_settings/#admin.gloo.solo.io.WorkspaceSettingsSpec

### Browser Information

Linux Brave v1.42.97 (Aug 17th, 2022)

### Additional Context

![Screenshot from 2022-08-20 09-50-36](https://user-images.githubusercontent.com/1662662/185720707-96080d72-70c7-4a38-beeb-9fd81886526d.png)

**Comment by Rachael-Graham** [comment] 2022-08-26 14:41
dupe of https://github.com/solo-io/doctopus/issues/30 and https://github.com/solo-io/doctopus/issues/51

**Closed by Rachael-Graham** 2022-08-26 14:41 UTC
Labels: Type: Docs
