### ISSUE TITLE
Implement Helm tests

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1488] opened 2021-04-28 21:54 UTC
The Gloo Mesh and Gloo Mesh Enterprise helm charts offer many customization options for users at install time. We should have some test coverage for the helm chart to avoid introducing regressions as we add more features, and to verify that complex yet common install scenarios are supported by the chart.

**Comment by EItanya** [comment] 2021-06-17 12:20
Dupe of https://github.com/solo-io/gloo-mesh/issues/525

**Closed by EItanya** 2021-06-17 12:20 UTC
Labels: Type: Enhancement
